# Generated by Django 5.2.6 on 2025-12-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='price_per_unit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
