# Generated by Django 5.2.8 on 2025-12-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cost_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='profit',
            field=models.FloatField(),
        ),
    ]
